-- IPA Church Elappara media library setup
-- Run this ONCE in Supabase SQL Editor for project wgjoaitequtthyzufgev.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'site-media',
  'site-media',
  true,
  52428800,
  array['image/*','video/mp4','video/webm','video/quicktime']::text[]
)
on conflict (id) do update set
  name = excluded.name,
  public = true,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.site_media (
  id bigint generated by default as identity primary key,
  path text not null unique,
  kind text not null check (kind in ('image','video')),
  title text not null default '',
  caption text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.site_media enable row level security;

grant select on public.site_media to anon, authenticated;
grant insert, update, delete on public.site_media to authenticated;

drop policy if exists "Public can read site media" on public.site_media;
create policy "Public can read site media"
on public.site_media
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated can manage site media" on public.site_media;
create policy "Authenticated can manage site media"
on public.site_media
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can list site media" on storage.objects;
create policy "Authenticated can list site media"
on storage.objects
for select
to authenticated
using (bucket_id = 'site-media');

drop policy if exists "Authenticated can upload site media" on storage.objects;
create policy "Authenticated can upload site media"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'site-media');

drop policy if exists "Authenticated can update site media" on storage.objects;
create policy "Authenticated can update site media"
on storage.objects
for update
to authenticated
using (bucket_id = 'site-media')
with check (bucket_id = 'site-media');

drop policy if exists "Authenticated can delete site media" on storage.objects;
create policy "Authenticated can delete site media"
on storage.objects
for delete
to authenticated
using (bucket_id = 'site-media');
